---
# tasks file for web1
 - name: Install httpd
   yum: name={{service_name}} state=present
   yum: name={{service_name}} enabled=yes state=started
when: ansible_os_family == "RedHat"
 - name: Install git, ntp and vim
   yum: name={{ item }} state=present
   with_items:
      - git
      - ntp
      - vim
 - name: Ansible register variable basic example
    shell: "find *.txt"
    args:
      chdir: /Users/mdtutorials2/Documents/Ansible
    register: username
 - name:  group called “Deloitte”
    group: name=Deloitte
 - name: user called "deploy"
    user: name=deployr group=Deloitte
 - name: Copy Site Files
    template: src=templates/index.j2 dest={{ doc_root }}/index.html
